### ISSUE TITLE
ticker for UI refresh gets killed / doesn't start when opening app after alarm 

### ISSUE THREAD

**Issue by yattoz** [yattoz/Radio2#5]
Sometimes the timer that updates the UI isn't working when the app is started by the alarm intent. It's probably coming from the fact that when the service is started, PlayerStore is initialized by it, so the timer definition is skipped in the MainActivity onCreate.

**Comment by j-levy** [comment]
fixed in commit https://github.com/yattoz/Radio2/commit/11e36e14f243a28bdfd7180c9c1b71585336d6a6
